# SPDX-License-Identifier: GPL-3.0-only
"""Build the audited module, put its bytes in the authoring payload and pin player trust.

The player intentionally has NO project or assembly reference to ArrayRuntime.
It recovers that compiled module exclusively from the image and loads it in memory.
"""
import argparse
import base64
import gzip
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess

ROOT=Path(__file__).resolve().parent


def build(dotnet):
    environment=os.environ.copy()
    environment.update(DOTNET_CLI_TELEMETRY_OPTOUT='1',DOTNET_SKIP_FIRST_TIME_EXPERIENCE='1',DOTNET_GENERATE_ASPNET_CERTIFICATE='false')
    environment.setdefault('DOTNET_CLI_HOME',str(ROOT/'user_runs'/'dotnet-home'))
    if os.name=='nt':
        appdata=ROOT/'user_runs'/'appdata';appdata.mkdir(parents=True,exist_ok=True)
        environment['APPDATA']=str(appdata)
    for project in ('ArrayRuntime','OpticalPlayer','RuntimeTests'):
        subprocess.run([dotnet,'build',str(ROOT/'dotnet'/project/(project+'.csproj')),
                        '-c','Release','--nologo'],check=True,env=environment)
        if project=='ArrayRuntime':
            binary=ROOT/'dotnet'/'ArrayRuntime'/'bin'/'Release'/'net10.0'/'ArrayRuntime.dll'
            data=binary.read_bytes()
            if not 1<=len(data)<=131072:raise ValueError('Runtime module exceeds the player limit')
            sha=hashlib.sha256(data).hexdigest()
            payload={'format':'dotnet-il/gzip-base64','sha256':sha,
                     'data':base64.b64encode(gzip.compress(data,mtime=0)).decode('ascii')}
            (ROOT/'runtime-payload.json').write_text(json.dumps(payload,sort_keys=True,separators=(',',':'))+'\n',encoding='ascii')
            (ROOT/'dotnet'/'OpticalPlayer'/'TrustedRuntime.cs').write_text(
                '// SPDX-License-Identifier: GPL-3.0-only\n// Generated by build_player.py from the audited source build.\n'
                'namespace OpticalPlayer;\ninternal static class TrustedRuntime { public const string Sha256="'+sha+'"; }\n',encoding='ascii')
            print(json.dumps({'runtime_bytes':len(data),'encoded_runtime_bytes':len(payload['data']),'sha256':sha}))
    print('Built C# player: dotnet/OpticalPlayer/bin/Release/net10.0-windows/OpticalPlayer.exe')


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dotnet',default=shutil.which('dotnet'))
    args=parser.parse_args()
    if not args.dotnet:parser.error('Install the .NET 10 SDK or supply --dotnet')
    build(args.dotnet)

