// SPDX-License-Identifier: GPL-3.0-only
// Generated by build_player.py from the audited source build.
namespace OpticalPlayer;
internal static class TrustedRuntime { public const string Sha256="6638cfed6fb7cc877b495d714b8437cc8d04d46cb5ab52eb4ba5f9d38c75e4a9"; }
